spring:
  cloud:
    zookeeper:
      config:
        #将该值设置为false将禁用Zookeeper配置，默认true
        enabled: false
        #配置根节点名称，默认为config
        root: config
        #全局配置节点名称，默认为application
        default-context: application
        #设置服务名和环境名称之间的分隔符，默认为英文逗号
        profile-separator: ,
      connect-string: 192.168.42.128:2181
  profiles:
    active: dev
  config:
    import: "optional:zookeeper:"
