server:
  port: 6001
spring:
  application:
    name: spring-unity
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/dev
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.100.128
    port: 6379
    password: adminadmin
    #Redis中哪个库
    database: 1
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.example.springunity.pojo
  mapper-locations: classpath:mapper/**Mapper.xml