server:
  port: 6001
spring:
  application:
    name: spring-unity
  datasource:
    url: jdbc:mysql://127.0.0.1:3308/dev
    username: root
    password: adminadmin
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.18.242.206
    port: 6379
    # password: adminadmin
    database: 0 # Redis中哪个库
    jedis:
      pool:
        max-active: 1000 # 连接池最大连接数
        max-wait: -1ms # 连接池最大阻塞连接时间
        max-idle: 10 # 连接池中最大空闲数
        min-idle: 5 # 连接池中最小空闲数
    timeout: 6000ms # 连接超时时长
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  type-aliases-package: com.example.springunity.pojo
  mapper-locations: classpath:mapper/**Mapper.xml